a = float(input("Enter Homework grade: "))
b = float(input("Enter Midterm grade: "))
c = float(input("Enter Final Exam grade: "))
finalGrade = (a*0.45)+(b*0.25)+(c*0.30)
print("Your final grade is: ", round(finalGrade, 2))
