a = float(input("Enter homework grade: "))
b = float(input("Enter midterm grade: "))
c = float(input("Enter final exam grade: "))
finalGrade = (a*0.45)+(b*0.25)+(c*0.30)
print("Your final grade is", round(finalGrade, 2))
